# Generated by Django 5.2.5 on 2025-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Показывать посты с даты'),
        ),
    ]
